#import "../../../graphql/UserSettingsFragment.gql"

mutation AccountSetupFormUpdateMutation($input: UserUpdateInputArgs!, $where: WhereUniqueInputArgs!) {
  updateUser(data: $input, where: $where) {
    ...UserSettingsFragment
  }
}
