#import "../../../graphql/CustomerFragment.gql"

mutation DeleteCustomerMutation($where: WhereUniqueInputArgs!) {
  updateCustomer(data: { active: false }, where: $where) {
    ...CustomerFragment
  }
}
