#import "../../../graphql/DeductionFragment.gql"

mutation DeleteDeductionMutation($where: WhereUniqueInputArgs!) {
  updateDeduction(data: { active: false }, where: $where) {
    ...DeductionFragment
  }
}
