-- AlterTable
ALTER TABLE "invoice" ADD COLUMN     "conversion_date" TIMESTAMP(3),
ADD COLUMN     "conversion_rate" DOUBLE PRECISION,
ADD COLUMN     "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "subtotal_dkk" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total" DOUBLE PRECISION NOT NULL DEFAULT 0;
