export const invoiceStatuses = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  PENDING: 'PENDING',
  SENT_TO_COMPANY: 'SENT_TO_COMPANY',
  SENT_TO_COMPANY_NEEDS_CONTRACT: 'SENT_TO_COMPANY_NEEDS_CONTRACT',
  SENT_TO_COMPANY_CONTRACT_MADE: 'SENT_TO_COMPANY_CONTRACT_MADE',
  SENT_TO_COMPANY_AWAITING_APPROVAL: 'SENT_TO_COMPANY_AWAITING_APPROVAL',
  APPROVED_BY_COMPANY: 'APPROVED_BY_COMPANY',
  LATE_PAYMENT: 'LATE_PAYMENT',
  DEBT_COLLECTION: 'DEBT_COLLECTION',
  COMPANY_DISPUTE: 'COMPANY_DISPUTE',
  PAID: 'PAID',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_ON_HOLD: 'PAYMENT_ON_HOLD',
  CANCELLED: 'CANCELLED',
  DENIED_BY_COMPANY: 'DENIED_BY_COMPANY',
  SALARY_PAID: 'SALARY_PAID',
  SALARY_PAID_CUSTOMER_PAID: 'SALARY_PAID_CUSTOMER_PAID',
  SALARY_PAID_CUSTOMER_NOT_PAID: 'SALARY_PAID_CUSTOMER_NOT_PAID',
  MORE_INFO_NEEDED: 'MORE_INFO_NEEDED'
};

export const invoiceStatusesKeys: (keyof typeof invoiceStatuses)[] = Object.keys(
  invoiceStatuses
) as (keyof typeof invoiceStatuses)[];
