#import "../../../graphql/CooperationAgreementFragment.gql"

query CooperationAgreementDetailsQuery($where: WhereUniqueInputArgs!) {
  cooperationAgreement(where: $where) {
    ...CooperationAgreementFragment
  }
}
