#import "../../../graphql/CooperationAgreementFragment.gql"

mutation CreateCooperationAgreementFormMutation($input: CooperationAgreementCreateInputArgs!) {
  createCooperationAgreement(data: $input) {
    ...CooperationAgreementFragment
  }
}
