#import "../../../graphql/CustomerFragment.gql"

mutation EditCustomerFormUpdateMutation($input: CustomerUpdateInputArgs!, $where: WhereUniqueInputArgs!) {
  updateCustomer(data: $input, where: $where) {
    ...CustomerFragment
  }
}
