#import "../../../graphql/UserFragment.gql"

mutation EditUserFormUpdateMutation($input: UserUpdateInputArgs!, $where: WhereUniqueInputArgs!) {
  updateUser(data: $input, where: $where) {
    ...UserFragment
  }
}
