query CustomerSelectFieldQuery($where: CustomerWhereInputArgs) {
  # TODO: Make this a server side lookup if a user has more than a 100 customers.
  customers(orderBy: { name: asc }, first: 100, where: $where) {
    nodes {
      id
      name
    }
  }
}
