#import "../../../graphql/DeductionFragmentWithImage.gql"

mutation CreateDeductionFormMutation($input: DeductionCreateInputArgs!) {
  createDeduction(data: $input) {
    ...DeductionFragmentWithImage
  }
}
