#import "../../../graphql/CooperationAgreementFragment.gql"

mutation DeleteCooperationAgreementMutation($where: WhereUniqueInputArgs!) {
  updateCooperationAgreement(data: { active: false }, where: $where) {
    ...CooperationAgreementFragment
  }
}
