#import "../../../graphql/TaskFragment.gql"

mutation EditTaskFormUpdateMutation($input: TaskUpdateInputArgs!, $where: WhereUniqueInputArgs!) {
  updateTask(data: $input, where: $where) {
    ...TaskFragment
  }
}
