fragment CustomerFragment on Customer {
  id
  urn
  name
  email
  allowEarlyPayment
  address {
    id
    address
    region
    country {
      id
      name_en
    }
    city
    postalCode
  }
  user {
    id
    displayName
  }
  ean
  type
  paymentDueDays
  vatId
  contact
  phoneNumber
  economicCustomerId
  updatedDate
  createdDate
}
